# サウンド設定（最小構成）
sound_settings:
  commands: {}

# グローバル設定（必要最小限）
global_settings:
  master_volume: 1.0
  cache_sounds: true

# 音声生成設定（ミキサ初期化用の最小値）
generation_settings:
  sample_rate: 24000
  bit_depth: 16
  channels: 2
  buffer_size: 512
